In [12]:
#Description: This program predicts the price of Bitcoin for the next 30 days

import numpy as np 
import pandas as pd

In [13]:
#Load the data
# from google.colab import files # Use to load data on Google Colab
# uploaded = files.upload() # Use to load data on Google Colab

In [14]:
#Store the data into the variable df
df = pd.read_csv('BTC-USD.csv')

# Show the first 7 rows of the data
df.head(7)

         Date       Close
0  2015-10-25  283.679993
1  2015-10-26  285.299988
2  2015-10-27  293.787994
3  2015-10-28  304.618011
4  2015-10-29  313.855011
5  2015-10-30  328.015015
6  2015-10-31  314.165985

In [15]:
#Remove the Date column
df.drop(['Date'], 1, inplace=True)

# Show the first 7 rows of the new data set
df.head(7)

C:\Users\Juan\AppData\Local\Temp/ipykernel_4612/3759355046.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df.drop(['Date'], 1, inplace=True)

        Close
0  283.679993
1  285.299988
2  293.787994
3  304.618011
4  313.855011
5  328.015015
6  314.165985

In [16]:
#A variable for predicting 'n' days out into the future
prediction_days = 30 # n = 30 days

#Create another column (the target or dependent variable) shifted 'n' units up
df['Prediction'] = df[['Close']].shift(-prediction_days)

#Show the first 7 rows of the new data set
df.head(7)

        Close  Prediction
0  283.679993  320.045990
1  285.299988  328.205994
2  293.787994  352.683990
3  304.618011  358.041992
4  313.855011  357.381012
5  328.015015  371.294006
6  314.165985  377.321014

In [17]:
#Show the last 7 rows of the new data set
df.tail(7)

             Close  Prediction
2185  62026.078125         NaN
2186  64261.992188         NaN
2187  65992.835938         NaN
2188  62210.171875         NaN
2189  60692.265625         NaN
2190  61393.617188         NaN
2191  60930.835938         NaN

In [18]:
#CREATE THE INDEPENDENT DATA SET (X)

# Convert the dataframe to a numpy array and drop the prediction column
X = np.array(df.drop(['Prediction'],1))

#Remove the last 'n' rows where 'n' is the prediction_days
X= X[:len(df)-prediction_days]
print(X)

[[  283.679993]
 [  285.299988]
 [  293.787994]
 ...
 [43574.507813]
 [44895.097656]
 [42839.75    ]]

C:\Users\Juan\AppData\Local\Temp/ipykernel_4612/2554253737.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = np.array(df.drop(['Prediction'],1))

In [19]:
#CREATE THE DEPENDENT DATA SET (y) 
# Convert the dataframe to a numpy array (All of the values including the NaN's) 
y = np.array(df['Prediction']) 

# Get all of the y values except the last 'n' rows 
y = y[:-prediction_days] 
print(y)

[  320.04599    328.205994   352.68399  ... 60692.265625 61393.617188
 60930.835938]

In [20]:
# Split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [21]:
#Set prediction_days_array equal to the last 30 rows of the original data set from the price column
prediction_days_array = np.array(df.drop(['Prediction'],1))[-prediction_days:]
print(prediction_days_array)

[[42716.59375 ]
 [43208.539063]
 [42235.730469]
 [41034.542969]
 [41564.363281]
 [43790.894531]
 [48116.941406]
 [47711.488281]
 [48199.953125]
 [49112.902344]
 [51514.8125  ]
 [55361.449219]
 [53805.984375]
 [53967.847656]
 [54968.222656]
 [54771.578125]
 [57484.789063]
 [56041.058594]
 [57401.097656]
 [57321.523438]
 [61593.949219]
 [60892.179688]
 [61553.617188]
 [62026.078125]
 [64261.992188]
 [65992.835938]
 [62210.171875]
 [60692.265625]
 [61393.617188]
 [60930.835938]]

C:\Users\Juan\AppData\Local\Temp/ipykernel_4612/124858866.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  prediction_days_array = np.array(df.drop(['Prediction'],1))[-prediction_days:]

In [30]:
from sklearn.svm import SVR

# Create and train the Support Vector Machine 
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.00001) #Create the model
svr_rbf.fit(x_train, y_train) #Train the model

SVR(C=1000.0, gamma=1e-05)

In [31]:
# Print the predicted value
svm_prediction = svr_rbf.predict(x_test)
print(svm_prediction)

print()

#Print the actual values
print(y_test)

[ 4949.2625607    720.23987723 11071.75968647  8968.38741426
  4363.18221697 10769.55200849 11484.34807485 28030.37988034
  6356.2790344   8694.29111697 23695.7508483   4546.89373541
 24998.64272243 17468.90590283  5182.11444179   435.07633838
 24913.76660265  9350.6422436    420.72832758  2927.24784322
  9942.30848788  9210.62965243  5312.39867054  7234.65401409
  9561.23630316  7390.95215963  6300.26251224 22862.50222753
   436.36184215 22601.99200872  2995.51776079  9230.79381928
  4470.9098192   9384.52639894  8059.65239156 20713.62350965
  5776.56491871 23550.52362827  4001.2598415   3403.93053671
   442.50513405  3484.25024643  8370.6515913   7947.62684934
  9847.37967162 10724.51055587  9209.61571014   667.31670265
  7726.33401119  8671.84418647  1148.21814271  7892.86538656
  9229.61265568  9980.24188956   605.11792592  7519.232674
 27127.40980434  1136.38342465  4046.35565046  7921.74684619
  5775.32312199   470.93552719  6796.04348047   803.01210523
  6242.23666054 11451.16899583  4447.18764151  4083.52971894
  5107.96584974 23151.14743899  8978.54886598  1379.98406331
  9172.96081904   640.10522647   677.90192249  9800.37328778
  1963.74612871   647.6288623   6645.19197077   635.24316613
 23081.61432246   666.7491058   6740.30280211 11483.19133789
   416.32773386  7991.38262685  8312.14268038   649.12925942
   435.31170718  6246.5177337  24597.54764828  1625.33939443
   619.81929854  8691.85935281  9208.44417684  8977.20752913
  7898.2522943   2213.0275854    640.97410023  9291.51681409
   431.44782715  6277.24258722  9222.35285811   631.65878186
 25231.09032189 10787.56329134   862.040052   20385.95780412
  8234.05631342  9769.69496918   417.987629   21221.65324013
   682.4927683   3265.90680885   728.81743429  9223.75009483
  1162.54437092   487.28809017 18518.21128757 17334.40046896
 10917.92434651  9240.74977145 22121.30654898 26285.72302283
   438.2672974  20236.90251766   424.31658796  1183.22939825
  9240.07888605   461.0311919   2900.53283557   789.17040445
  9358.50546397   422.88437382  1219.27910287 16530.80511021
  3980.63867117  8178.76042742 25326.80298222  1411.72021686
 28151.90089715  9381.18399891  9234.51666043 11493.8375236
  1235.14378445   664.94066408  4464.57062906  9375.88418614
  3368.20734825 22521.03897466 10139.59746812  8798.42806571
 17358.07194461  4469.41210186  1195.1733241   6597.88194603
  5251.486852   10701.7882518    421.46283813 22174.87727604
  9138.53393149  6697.91785802 23026.72754121  9248.48192508
   774.78726065  9358.70801387  8752.46889544  1972.51638812
 26291.19205704  8056.26134541  7216.91620894 17147.06574622
  4678.86850042   718.02126458  9525.74512273  8065.41798808
   778.65607219 15502.71447071  6539.5108058  11512.3333786
  4030.30050382  6241.74198698  7519.54460316   654.34848972
  9166.41223748   771.72789058 18975.70838638  3979.71534649
   640.88518895  7785.74500107  8700.62856258   830.94185993
  9213.46000309  6257.09242481 10809.05599356  9098.64842033
 10831.23672412  5328.17623893  7891.10843125  2716.12386395
  9623.24983885  6264.15500217  1189.39010296   437.16147827
  9161.8072825  17274.53547457  1650.23660166  6452.07516575
   468.75799403 15704.83957152  1123.97045828  9507.96910605
  3999.31367073 19257.1630068   4232.74966682  1789.35839861
 16801.90839006   414.02683736 21815.04921918   449.54011976
  8636.99985227  8866.33715857  4679.07693793  4961.28556814
  1196.35715458 26097.77317939 20410.54520497  3989.85120994
 11538.16361964  1743.00909067 17167.31399543 22765.41663418
  6516.95219633 10790.7158013   9813.40927032   639.58436226
 19571.45515341  6287.24332507 16804.82046145 17771.70487828
  5013.89551045  5436.11173287  9197.21361262  9829.68247388
  1131.95277606  8253.84132883  3963.22540055  6277.90563655
 10146.25248552  9068.55408581  8715.37742495   466.86224756
  1183.53268692  8923.12901004   441.99965114   653.65420398
  9222.69571302  8368.75882475  6322.05223171  7599.61686788
  9441.8263937  11113.84399825  9744.70506796  6409.48381641
   673.90621253  2713.05586464   674.61842824  9644.63870995
  4537.81575453  9250.98028198 11462.80251726  4771.98575574
  5455.38653436 19285.63051469   433.95932809   917.58793781
 19901.92018722  9709.82437985 10725.24255509 11484.67754852
  9880.37510028 10754.24702818  9448.4280856   8933.36822679
  9196.44882053  9391.76688728  9455.10090139   458.52848507
  7399.90321966 26577.68585284 21085.50861012 23748.11508953
  3961.95934357  6276.38325906  9715.73600668  1111.21056052
  3901.07428505  7375.34544121  6329.95687701  4625.51614886
   457.83720741   675.49012422  3947.45843225 11061.84143
   595.46936907   439.07334054  9317.87082269   682.03059347
  9556.45506225  8206.35443437   650.887593   18618.17750238
   918.61466476 25132.69360577   647.05068131 22928.67374289
  9165.57077476  9242.02675438  9220.03538621  9527.6036137
  8107.49518055  4948.73552881   843.41216467  1216.46765768
  4975.12888982  2783.0816029   9335.63107706   421.61260726
  8494.81843495   642.42852147  7956.38520881 24357.09678174
  9250.11696189  9149.21136379  9350.37669236  3967.48359775
  6406.25998932  7495.33415656  4292.31782179  8782.5081942
 10731.60959711  9298.20405461  6414.10407221  9614.07023168
 15505.78328624  7785.74500107  9668.93955178  1227.22789047
  8197.15299129  8605.27345418 22501.0577123   7714.06773674
   639.99202886  7279.48178836 23757.65675988 19612.83678462
  5730.21788521  4111.7008276   6937.44043825   674.30814544
  9517.01721646   637.59081228  9347.34171175  9901.4893896
   421.0192789   3831.43658846   418.66007019   671.12622683
   505.84793158 21627.92313687  9735.42871872   441.20914239
   422.3296501  10703.69880316  7361.68815955 20030.95231626
  2380.91597525  4851.20455308  9360.69887419  3525.38244968
  7836.45510593  1701.1874718   9514.59327919   449.27030276
 21202.67776385  4810.93902427  2714.44474603  3988.79319841
 23968.3053833   2886.3415119   6623.76453022   499.23284496
  4655.96061471  7641.1639638   8437.97929162  5751.60586187
  8993.90446855  4289.8687067   6450.75260203 11425.25456435
 11391.69256111  1145.81032959  9143.80817853  9242.0477657
   455.1442285  19716.70795595  9210.02655146  9233.07742797
  9113.02339083 16349.77187076  6886.06751553  5434.17627647
  9181.96440234  4891.51188487 10057.70256655  9245.53423098
   765.13762878  9241.87320978 26244.00291438 24751.71972738
 20929.05861497   751.80865693  9915.12897654  5088.187692
 17081.17061247  7367.49674399  4064.74347804  9243.10226429
  5018.52065199  9637.75253939   416.15387926  6649.63959488
 10865.06687933]

[ 3154.949951   606.271973 13737.109375  8300.860352  6011.450195
 17817.089844 10690.400391 38402.222656  6290.930176  9697.5
 56396.515625  4151.52002  40693.675781 18803.65625   2947.709961
   411.623993 47105.515625 10138.517578   400.570007  2038.869995
 11246.348633  7047.160156  4382.879883  6276.120117  7556.237793
  7397.796875  4871.490234 35862.378906   435.690002 61393.617188
  2754.860107  6733.387207  5708.52002   6550.160156  6753.120117
 59095.808594  2478.449951 39995.90625   3896.375     2398.840088
   417.131012  4087.659912  8790.919922  8052.543945 10621.664063
  9911.841797  9510.200195   711.619019  7370.779785  6502.589844
  1079.97998   5829.501465 11208.550781  8205.369141   639.890015
 10058.799805 47092.492188  1061.349976  2357.899902  7881.84668
  2721.790039   387.490997  6409.220215   864.539978  3753.994873
  8879.620117  6130.529785  4879.87793   4781.990234 33992.429688
  9870.094727  1555.449951  9240.549805   604.728027   567.23999
  8103.911133  1071.790039   623.508972  6385.620117   575.536987
 40797.609375   702.031006  6461.009766  6973.529785   432.152008
  9818.349609  7978.309082   610.435974   380.289001  3424.588135
 59793.234375  1723.349976   572.302979  8808.262695  6719.959961
  9373.009766  7790.149902  2443.639893   609.874023 10326.054688
   374.447998  3880.76001   9525.363281   463.615997 61553.617188
 10345.810547   988.674011 38903.441406  5982.45752   4970.788086
   409.548004 65992.835938   371.294006  2175.469971   770.809998
  7633.759766  1207.209961   433.437988 11225.299805  7621.299805
 11382.616211  8909.954102 58870.894531 33746.003906   416.729004
 36630.074219   395.536011  1250.150024  6242.193848   443.187988
  2744.909912   921.984009  9240.34668    394.971985  1036.73999
 18802.998047  3616.880859  7987.371582 54207.320313  1537.670044
 42235.730469  9313.610352 14291.5      10051.704102  1188.48999
   716.411011  2574.790039  8672.455078  2228.409912 51206.691406
  6890.52002   9395.009766 15170.099609  4200.669922  1231.920044
  6359.490234  4578.77002   6853.839844   416.394012 37002.441406
 11961.269531  6495.839844 49546.148438  7269.68457    665.684998
  9529.803711  8912.654297  1182.680054 33155.847656  7884.90918
  8205.167969 10221.099609  5167.722168   780.55603  11410.525391
  9330.549805   834.281006 19445.398438  7143.580078  9900.767578
  2286.409912  8658.553711  7410.656738   641.072021 10767.139648
   973.497009 34616.066406  3960.911133   609.734985  6305.799805
  8601.795898  1013.380005  6582.359863  3521.101807 10366.700195
  7902.089844 16317.808594  4001.73999   7708.990234  4371.600098
 14606.5       6602.950195  1221.380005   368.766998  9159.040039
  8926.570313  1039.969971  6321.200195   766.307983 11359.400391
  1173.680054  8058.669922  3911.484375 34269.523438  4597.120117
  1724.23999  11440.700195   424.029999 46196.464844   423.989014
  6786.02002  10583.134766  4073.26001   2589.409912  1100.22998
 35698.296875 62026.078125  4030.8479   13654.21875   1839.089966
 17150.623047 48378.988281  7459.689941 11478.168945  7569.629883
   606.973022 37304.691406  7688.077148 10931.400391 18264.992188
  6153.850098  3552.953125 10141.996094  7531.97998    901.541992
  7271.208008  3924.369141  5554.330078  9630.664063  9348.480469
  7344.884277   577.469971   921.590027 11323.200195   414.81601
   689.651001  6681.062988  8192.150391  7321.040039  6710.629883
  9934.433594 14982.099609  8321.756836  3419.937256   579.651001
  2564.060059   586.752991 10167.268555  2488.550049  7400.899414
  9664.730469  4772.02002   4163.069824 13772.         417.562988
   899.072998 46391.421875 10181.641602 10680.837891 10623.540039
 11573.299805 11112.700195 11011.102539  8813.582031  6834.759766
 10131.055664  8838.375      572.72699   6385.819824 31796.810547
 58917.691406 11188.599609  3620.810791  4365.939941 10599.105469
  1166.719971  3657.839355  6597.549805  6388.439941  5204.958496
   410.938995   573.911987  3905.227295 10085.62793    647.000977
   379.653992  9758.852539   665.012024  9665.533203  6880.323242
   632.828003  9870.303711   358.041992 39974.894531   626.315979
 45585.03125   9045.390625  9475.277344  7653.97998   6763.189941
  7707.770996  3576.032471   907.679016  1272.829956  5753.089844
  2710.669922  7514.470215   450.303986  8596.830078   598.211975
  3242.484863 54529.144531  8251.845703  7463.105957  9278.807617
  3906.717285  6588.310059  8165.009766  2407.879883  8367.847656
 10462.259766  9461.058594  4257.419922 10360.546875 10868.400391
  6308.52002  11878.111328  1054.22998  10144.556641  9268.761719
 57332.089844  8897.46875    606.166016  7550.900879 61572.789063
 55859.796875  2548.290039  4069.107178  2372.560059   569.947021
 10855.371094   608.04303   7624.919922 11205.892578   420.785004
  2705.409912   391.726013   587.801025   629.367004 35697.605469
  9228.325195   413.971985   421.563995 10774.426758  7814.915039
 49944.625     1133.25      2732.159912  7176.414551  4352.399902
  6639.140137  1172.52002   7334.098633   382.492004 36702.597656
  5210.515625  2601.639893  3687.365479 36926.066406  2576.47998
  6371.27002    422.822998  3836.741211  9358.589844 19140.800781
  4325.129883  9324.717773  5904.830078  4582.959961 15565.880859
 10231.744141  1179.969971  9276.5      14026.599609   623.97699
 35547.75      6185.066406  9190.854492  7096.279785 18699.765625
  7795.601074  4193.700195 10185.5       2805.620117 10347.712891
  9439.124023   933.197998  9629.658203 55888.132813 58245.003906
 37575.179688   465.321014  9332.34082   3728.568359  8736.980469
  7954.12793   3678.924561 10116.673828  5251.937988  8078.203125
   441.389008  6544.430176 10585.164063]

In [32]:
# Print the model predictions for the next 'n=30' days
svm_prediction = svr_rbf.predict(prediction_days_array)
print(svm_prediction)

[20788.09075342 19745.82584995 19328.95642985 19127.75377011
 19209.87474085 20406.42632139 20927.85050396 22853.29453768
 20537.33888496 27084.03796357 21381.39248964 19517.35586296
 19174.01032507 19832.52530218 21496.78557866 21563.46690838
 24375.52335056 24664.73554418 23439.98675185 22399.45188077
 19521.36726477 19191.98866353 19611.69684965 18363.90933482
 18236.89400112 18233.59637408 18251.19920623 19376.17730477
 19762.73008304 19175.44671336]

In [33]:
#Print the actual price for the next 'n' days, n = prediction_days=30 
df.tail(prediction_days)

             Close  Prediction
2162  42716.593750         NaN
2163  43208.539063         NaN
2164  42235.730469         NaN
2165  41034.542969         NaN
2166  41564.363281         NaN
2167  43790.894531         NaN
2168  48116.941406         NaN
2169  47711.488281         NaN
2170  48199.953125         NaN
2171  49112.902344         NaN
2172  51514.812500         NaN
2173  55361.449219         NaN
2174  53805.984375         NaN
2175  53967.847656         NaN
2176  54968.222656         NaN
2177  54771.578125         NaN
2178  57484.789063         NaN
2179  56041.058594         NaN
2180  57401.097656         NaN
2181  57321.523438         NaN
2182  61593.949219         NaN
2183  60892.179688         NaN
2184  61553.617188         NaN
2185  62026.078125         NaN
2186  64261.992188         NaN
2187  65992.835938         NaN
2188  62210.171875         NaN
2189  60692.265625         NaN
2190  61393.617188         NaN
2191  60930.835938         NaN

In [34]:
#Print the actual price for the next 'n' days, n=prediction_days=30 
dp = pd.DataFrame(svm_prediction, columns = ["Prediction"])
dp.tail(prediction_days)

      Prediction
0   20788.090753
1   19745.825850
2   19328.956430
3   19127.753770
4   19209.874741
5   20406.426321
6   20927.850504
7   22853.294538
8   20537.338885
9   27084.037964
10  21381.392490
11  19517.355863
12  19174.010325
13  19832.525302
14  21496.785579
15  21563.466908
16  24375.523351
17  24664.735544
18  23439.986752
19  22399.451881
20  19521.367265
21  19191.988664
22  19611.696850
23  18363.909335
24  18236.894001
25  18233.596374
26  18251.199206
27  19376.177305
28  19762.730083
29  19175.446713